version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: env_tech_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: env_tech
      MYSQL_PASSWORD: admin
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - /var/lib/mysql
    ports:
      - 3306:3306
  phpmyadmin:
    container_name: env_tech_pma
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - 8080:80
    restart: always
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: admin